### ISSUE TITLE
貌似不能用

### ISSUE THREAD

**Issue by JinghuangLiu** [shingwasix/MobShareSDK#5]
如题，我试了下，貌似无法正常使用。提示：

Installing MobShareSDK (2.12.0)
[!] Error installing MobShareSDK
[!] /usr/bin/git clone https://github.com/shingwasix/MobShareSDK.git /var/folders/v3/7bgzc_6s2v15vc1pr71x13rh0000gn/T/d20151006-4814-1tggevd --single-branch --depth 1 --branch 2.12.0

Cloning into '/var/folders/v3/7bgzc_6s2v15vc1pr71x13rh0000gn/T/d20151006-4814-1tggevd'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by shingwasix** [comment]
这是网络错误，请换个时段再安装试试，或翻墙后再安装。大天朝的网络，你懂的。

**Comment by JinghuangLiu** [comment]
换过网络和时段，试了4次，其他都行，就这个有问题。

发自我的 iPhone

**Comment by shingwasix** [comment]
你在终端执行`git clone https://github.com/shingwasix/MobShareSDK.git --single-branch --depth 1 --branch 2.12.0`看看能否克隆成功，如果还是出现那个错误的话，可以参考以下两个网页解决。
http://stackoverflow.com/questions/26197171/git-clone-repository-error-rpc-failed-result-56-http-code-200
https://confluence.atlassian.com/pages/viewpage.action?pageId=693897332

**Comment by JinghuangLiu** [comment]
那个克隆是成功的

发自我的 iPhone

**Comment by shingwasix** [comment]
那将`/var/folders/v3/7bgzc_6s2v15vc1pr71x13rh0000gn/T/d20151006-4814-1tggevd`这个文件夹删掉，再执行一次pod install试试吧

**Comment by JinghuangLiu** [comment]
ShareSDK iOS端现在就是我在更新和维护。我们其实也考虑过支持cocoapod，但是ShareSDK v2.x 包太多了，如果考虑分包感觉体验不是很好。我看到你的后就想试下，如果体验好的话，也正式支持下。能给我你的QQ吗，或者加下我，我的QQ：642270023。

发自我的 iPhone
