### ISSUE TITLE
只下载了中文的本地化文件。

### ISSUE THREAD

**Issue by VincentSit** [shingwasix/MobShareSDK#8]
我的项目需要支持英文环境，但我发现下载下来的只有中文的本地化文件，我查看了 podspec，你只指定的中文的本地化文件，为什么不同时指定英文的呢？

https://github.com/shingwasix/MobShareSDK/blob/master/MobShareSDK.podspec#L19

**Comment by shingwasix** [comment]
你说的这个问题，在我制作初版的时候已经发现，当时没有找到合适的处理方法。
你可以使用用官方的试试看，地址如下：
https://github.com/MobClub/ShareSDK-for-iOS
官方版本我测试过是可行的。
因为Mob官方已参考本项目在自己的项目上添加了cocoapods支持，所以本项目已经停止维护。但不排除日后官方版本易用性过低或其它原因而导致本项目重新启动的情况出现。
欢迎你在使用官方版本的同时继续关注本项目：）

**Comment by VincentSit** [comment]
我刚才 fork 了试了下修改，确实有问题。

谢谢了。
